; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
lib_deps =
  adafruit/Adafruit SH110X
  adafruit/Adafruit MPU6050
  adafruit/DHT sensor library
  bblanchon/ArduinoJson
  dfrobot/DFRobotDFPlayerMini
build_src_filter =
  -<main.cpp>
  -<max98357_test.cpp>
  -<inmp441_test.cpp>
  -<dfplayer_test.cpp>
  -<laptop_mp3_sing.cpp>
  +<wifi_max_stream.cpp>
  -<mpu_oled_test.cpp>
