const fs = require('fs');
let web = fs.readFileSync('web_serial_server.js', 'utf8');

const missingHtml = `</style></head><body class="auth"><main class="authWrap"><section class="authHero"><div class="brandMark"><div class="botIcon"><span class="ant l"></span><span class="ant r"></span><span class="halo"></span><div class="botHead"><span class="botEye l"></span><span class="botEye r"></span></div></div><div class="brandText"><strong>GemBot</strong><span>Mini AI Companion</span></div></div></section><section class="authCard"><h2 id="authTitle" class="authTitle">Buat akun baru</h2><p id="authSub" class="authSub">Hanya butuh beberapa detik</p><div class="field" id="nameField"><label>Nama Panggilan</label><div class="inputBox"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg><input type="text" id="authName" placeholder="Nama kamu..."></div></div><div class="field"><label>Email Pintar</label><div class="inputBox"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/><polyline points="22,6 12,13 2,6"/></svg><input type="email" id="authEmail" placeholder="kamu@email.com"></div></div><div class="field"><label>Kata Sandi</label><div class="inputBox"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="11" width="18" height="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg><input type="password" id="authPass" placeholder="••••••••"></div></div><button id="authSubmit" class="authBtn">Daftar Sekarang</button><div class="authSwitch"><span id="switchText">Sudah punya akun?</span> <button id="modeSwitch">Masuk di sini</button></div>`;

web = web.replace('<div id="authStatus" class="authMsg"></div></section></main>${floatingChatbotHtml()}<script>', missingHtml + '\n<div id="authStatus" class="authMsg"></div></section></main>${floatingChatbotHtml()}<script>');

fs.writeFileSync('web_serial_server.js', web);
console.log('Fixed HTML syntax error in pageHtml!');
